name       : spice-vdagent
version    : 0.17.0
release    : 8
source     :
    - https://www.spice-space.org/download/releases/spice-vdagent-0.17.0.tar.bz2 : f14a8bd8cdee10641aabd9ba32461a5844eab0fddb2a10c1d31386e7a9f7b33d
license    : GPL-3.0
component  : desktop.library
summary    : Spice agent for Linux guests
description: |
    Spice agent for Linux guests offering the following features:
    * Client mouse mode (no need to grab mouse by client, no mouse lag)
      this is handled by the daemon by feeding mouse events into the kernel
      via uinput. This will only work if the active X-session is running a
      spice-vdagent process so that its resolution can be determined.
    * Automatic adjustment of the X-session resolution to the client resolution
    * Support of copy and paste (text and images) between the active X-session
      and the client
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(pciaccess)
    - pkgconfig(spice-protocol)
    - pkgconfig(xfixes)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
setup      : |
    %patch -p1 < $pkgfiles/0001-Only-start-vdagent-under-virtualisation.patch
    %patch -p1 < $pkgfiles/security/cve-2017-15108.patch

    # place udev rules file in /usr/lib64 instead of /lib
    sed -i 's|udevrulesdir = /lib|udevrulesdir = /usr/lib64|' Makefile.am

    %reconfigure --with-session-info=systemd --with-init-script=systemd
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var/run
    rmdir $installdir/var
    install -D -m00644 $pkgfiles/spice-vdagent.tmpfiles $installdir/%libdir%/tmpfiles.d/spice-vdagent.conf

    # Preenable service
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../spice-vdagentd.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.

    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
